In [1]:
# Create an array with values ranging from 12 to 38"
import numpy as np 

arr = np.arange(12,38)
arr

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [16]:
#Add a border around an existing array
arr1=np.ones((3,3))
pad_arr=np.pad(arr1,pad_width=1,mode='constant',constant_values=0)
print(pad_arr)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
## Exercise 3: Convert a list and tuple into arrays"

lst1 = [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37]
print(lst1)
lst2= np.array(lst1)
print(lst2)
tup1 = (12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37)
print(tup1)
tup2 = np.asarray(tup1)
print(tup2)

[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
(12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37)
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [37]:
##Exercise 4:  Convert the values of Centigrade degrees into Fahrenheit degrees

arr1 = np.arange(12,38)
print(arr1)
for i in arr1:
    far = ((9 * i )/ 5 + 32)
    print(far)


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
53.6
55.4
57.2
59.0
60.8
62.6
64.4
66.2
68.0
69.8
71.6
73.4
75.2
77.0
78.8
80.6
82.4
84.2
86.0
87.8
89.6
91.4
93.2
95.0
96.8
98.6


In [47]:
## Exercise 5: Write a NumPy program to find the number of elements of an array, 
#length of one array element in bytes and total bytes consumed by the elements. "

arr1= np.arange(12,50)
print(arr1)
np.size(arr1)
arr1.itemsize
arr1.nbytes


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


304

In [65]:
## Exercise 6: Get the unique elements of an array
arr1 = [10,10,20,20,30,30]
np.array(arr1)
np.unique(arr1)
arr1 =np.array([10,20,10,10,20,20,30,10,20,10,20,10,20,10,20,10])
print(arr1)
arr2=arr1.reshape(4,4)
print(arr2)
np.unique(arr2)

[10 20 10 10 20 20 30 10 20 10 20 10 20 10 20 10]
[[10 20 10 10]
 [20 20 30 10]
 [20 10 20 10]
 [20 10 20 10]]


array([10, 20, 30])

In [69]:
## Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive"
x = np.linspace(2.5,6.5,30)
print(x)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


In [75]:
# Exercise 9: Convert 1-D arrays as columns into a 2-D array
arr1 = np.arange(10,20)
arr2 = np.arange(20,30)
print(arr1)
print(arr2)
arr3 = np.column_stack((arr1,arr2))
print(arr3)

[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29]
[[10 20]
 [11 21]
 [12 22]
 [13 23]
 [14 24]
 [15 25]
 [16 26]
 [17 27]
 [18 28]
 [19 29]]


In [83]:
## Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4
arr1 = np.zeros((5,5))
print(arr1)
arr1 +=np.arange(5)
print(arr1)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [97]:
import numpy as np
x = np.arange(1, 100)
print(x)
# find  multiple of 3 or 5
n= x[(x % 3 == 0) | (x % 5 == 0)]
print(n)
# print sum the numbers
print(n.sum())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [114]:
## Exercise 12: Combine a one and a two dimensional array together and display their elements\n"
x= np.arange(4)
print(x)
y= np.arange(8)
z=y.reshape(2,4)
print(z)
for a, b in np.nditer([x,z]):
    print("%d:%d" % (a,b),)
    
  


[0 1 2 3]
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


In [124]:
## Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.
arr1 = np.array([[0.42436315, 0.48558583, 0.32924763],[0.7439979,0.58220701,0.38213418],[0.5097581,0.34528799,0.1563123]])
print(arr1)
arr1[arr1 > .5] = .5
print(arr1)

[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
[[0.5        0.5        0.5       ]
 [0.7439979  0.58220701 0.5       ]
 [0.5097581  0.5        0.5       ]]


In [143]:
# Exercise 14: Add a new row to an empty numpy array"
arr1 = np.array([])
print(arr1)
np.append(arr1,np.array([0,1,2,3]),axis=0)
arr2 = np.empty((0,3),int)
print(arr2)
arr2 = np.append(arr2,np.array([[0,1,2]]),axis=0)
arr2 = np.append(arr2,np.array([[3,4,65]]),axis=0)
print(arr2)



[]
[]
[[ 0  1  2]
 [ 3  4 65]]


In [152]:
arr1 = np.array([1,2,3])
print(arr1)
arr2 = np.array([4,5,6])
print(arr2)
z=np.vstack([arr1,arr2])
print(z)
x = np.array([[1], [2], [3]])
y = np.array([[2], [3], [4]])
print(x)
print(y)
np.vstack((x,y))

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]]
[[2]
 [3]
 [4]]


array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [148]:
np.vstack([arr1,arr2])

array([[1, 2, 3],
       [4, 5, 6]])